### DISCUSSION TITLE
Running Multiple Instances

### DISCUSSION THREAD

**Discussion by amxmln** [electerious/Ackee#344] [Q&A]
Hi there! I’m looking to migrate from Umami to Ackee and since I’m also hosting analytics for a friend and wouldn’t want their data to pollute mine in the overview (and not share my credentials with them), I was thinking of running two instances of Ackee in parallel as stated in the FAQ.

Would you be able to provide a bit more guidance on how to do that?

Ideally I’d like to be able to:

- Have a single Ackee folder with the most recent version
- Two sets of `.env` files with the configuration information for each instance
- Start and stop both instances at the same time when doing maintenance

You mention that both instances can connect to the same MongoDB – how does Ackee know which data to show in which instance in that case?

Thank you for your library and time. :tada:

**Comment by electerious** [comment]
You can start multiple instances of Ackee using Docker compose. Here's an example of the relevant `docker-compose.yml` part:

```yml
  ackee_one:
    image: electerious/ackee
    container_name: ackee_one
    restart: always
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee_one
      - ACKEE_PORT=80
      - ACKEE_USERNAME=username
      - ACKEE_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - isolated_nw
  ackee_two:
    image: electerious/ackee
    container_name: ackee_two
    restart: always
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee_two
      - ACKEE_PORT=80
      - ACKEE_USERNAME=username
      - ACKEE_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - isolated_nw
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    volumes:
      - /srv/mongo/data:/data/db
    networks:
      - isolated_nw
```

The instances know how to keep the data separated, because they don't share the same connection URI (`mongodb://mongo:27017/ackee_one` vs `mongodb://mongo:27017/ackee_two`).

I hope that helps! :)
