### ISSUE TITLE
Traefik integration

### ISSUE THREAD

**Issue by ghost** [electerious/Ackee#66]
Hello. I spiked on a Traefik integration yesterday using a mirror of this software as I'm investigating alternatives to Fathom for use in [After Dark](https://after-dark.habd.as). I'm dropping the code I wrote yesterday here along with some notes as I took it as far as I have time for right now. Hopefully someone will see it to the finish line and get a functional test case together for Ackee integration with Traefik.

```yml
version: "3.7"
services:

  traefik:
    image: traefik:v2.0.0
    restart: always
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik Web UI (enabled by --api.insecure)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      # - ./traefik.toml:/etc/traefik/traefik.toml # Start using config

  web:
    build: .
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./site/content:/opt/after-dark/content/:ro
      - ./site/config.toml:/opt/after-dark/config.toml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.after-dark.entrypoints=web
      - traefik.http.routers.after-dark.rule=Host(`test.local`)

  ackee:
    image: electerious/ackee
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee
      - ACKEE_USERNAME=ackee
      - ACKEE_PASSWORD=ackee
    labels:
      - traefik.enable=true
      - traefik.http.routers.ackee.entrypoints=web
      - traefik.http.routers.ackee.rule=Host(`ackee.test.local`)
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,POST,PATCH,OPTIONS"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=origin-list-or-null"
      - "traefik.http.middlewares.testheader.headers.accessControlAllowHeaders=Content-Type"

  mongo:
    image: mongo:4.2-bionic
    restart: always
    volumes:
      - db-data:/var/lib/mongodb

volumes:
  db-data:
```

Resources

- https://docs.traefik.io/middlewares/headers/#cors-headers - CORS docs
- https://github.com/containous/traefik/issues/5567 - CORS issue (open at present)

Notes:

- `localhost` hardcoded in `src/index.js` must be changed to `0.0.0.0` for ackee to work properly
- you may run `docker-compose exec ackee sh` and hack `index.js` at runtime then, inside the running ackee container, do a `kill <pid>` where <pid> is ackee. the container will restart automatically based on the compose rules and be listening on the correct port and you won't need for fork to do this
- if you're trying to do this with after-dark (linked above) as `web` you can disable CSP for testing purposes via the setting in `config.toml`

Cheers.

**Comment by jhabdas** [comment]
<img width="615" alt="Screen Shot 2019-12-04 at 10 24 12" src="https://user-images.githubusercontent.com/58496751/70108901-6473e600-1685-11ea-83f4-60ff6b2d6d35.png">

**Comment by electerious** [comment]
> localhost hardcoded in src/index.js must be changed to 0.0.0.0 for ackee to work properly

Will add this as an option `HOST` or `ACKEE_HOST`, but do you think that going with `0.0.0.0` as the default could be problematic for some users?

**Comment by eskan** [comment]
Hi,
if it helps Ackee works fine with traefik 1.7 and this labels (traefik-net is the network name traefik use)

```
      labels:
        traefik.port: "3000"
        traefik.docker.network: "traefik-net"
        traefik.frontend.rule: "Host:stats.my-host.com"
        traefik.frontend.headers.customResponseHeaders: 'Access-Control-Allow-Methods: GET, POST, PATCH, OPTIONS||Access-Control-Allow-Origin: *||Access-Control-Allow-Headers: Content-Type'
```
